add function send_messages
bogdanburich/fyst_fest_bot pull request #9
Opened 2023-05-17 10:39 UTC by SelfMullerMikhail

2023-05-17 11:20 UTC, bogdanburich requested changes

2023-05-17 11:20 UTC, bogdanburich commented on app/utils.py
> +async def try_send_message(customer_counter: int,
Не понятно, зачем это выносить в отдельную функцию и почему она возвращает количество пользователей.
Название переменной customers_count - не очень удачное, это users, а не customers.

2023-05-17 11:20 UTC, bogdanburich commented on app/utils.py
> +        if customer_id not in ADMIN_IDS:
Если пользователь админ, но не автор сообщения, то он тоже должен получить сообщение.

2023-05-17 11:20 UTC, bogdanburich commented on app/utils.py
> +    message_text = context.chat_data[user_id]
Так будет лаконичнее и лучше читаться

message_text = context.chat_data[user_id]
ontext.chat_data[user_id] = message_text

2023-05-17 11:20 UTC, bogdanburich commented on app/utils.py
> +    call_del = 'delete__'
Вот это как будто бы лишним выглядит. Зачем отправлять сообщение "0 people got message", если его нужно просто удалить? Непонятно.

2023-05-17 11:20 UTC, bogdanburich commented on app/bot.py
> +        if context.chat_data[user_id] == "send_message":
Одинарные кавычки здесь и ниже

2023-05-17 11:20 UTC, bogdanburich commented on app/bot.py
> +            context.chat_data[user_id] = "send_message"
Непонятно, зачем это нужно

2023-05-17 11:23 UTC, bogdanburich commented on app/utils.py
> +    for customer_id in context.chat_data:
По-моему, пользователи вообще не будут получать сообщения.

2023-05-17 11:36 UTC, SelfMullerMikhail commented on app/utils.py
> +    except error.BadRequest:
если пользователь остановил бота, но его id сохранится в контексте.

2023-05-17 11:38 UTC, bogdanburich commented on app/utils.py
> +    except error.BadRequest:
Мне вообще не нравится идея сохранять id в контекст. Разве нет метода, чтобы отправить сообщение всем активным пользователям?

2023-05-17 11:38 UTC, SelfMullerMikhail commented on app/utils.py
> +async def try_send_message(customer_counter: int,
Выношу, что бы если происходило исключение, то не выбивало всю функцию. 
Названия разделил, так как user_id это тот, кто отправляет сообщение, а кастомерыте кто получают.
Возвращает для удобства просто. Что бы быть осведомлённым. Сколько людей получило месседж.

2023-05-17 11:39 UTC, SelfMullerMikhail commented on app/utils.py
> +        if customer_id not in ADMIN_IDS:
понял.

2023-05-17 11:39 UTC, SelfMullerMikhail commented on app/utils.py
> +    message_text = context.chat_data[user_id]
Спасибо!

2023-05-17 11:40 UTC, SelfMullerMikhail commented on app/utils.py
> +    call_del = 'delete__'
Извини, не понял(

2023-05-17 11:40 UTC, bogdanburich commented on app/utils.py
> +    except error.BadRequest:
Посмотри issue: https://github.com/python-telegram-bot/python-telegram-bot/issues/1836

2023-05-17 11:42 UTC, SelfMullerMikhail commented on app/bot.py
> +            context.chat_data[user_id] = "send_message"
Добавляем состояние пользователя. Что бы следующее его сообщение вызвало функцию 'get_apply'

2023-05-17 11:42 UTC, SelfMullerMikhail commented on app/utils.py
> +    for customer_id in context.chat_data:
Почему? Контекст действует только в рамках одного пользователя? Или всех пользующихся ботом?

2023-05-17 11:42 UTC, SelfMullerMikhail commented on app/bot.py
> +    flag = False
+

2023-05-17 11:43 UTC, SelfMullerMikhail commented on app/utils.py
> +    callback_button_send = InlineKeyboardButton("Send", callback_data=call)
+

2023-05-17 11:45 UTC, bogdanburich commented on app/utils.py
> +    except error.BadRequest:
Если метода нет, то нужно подумать. Хранить сообщение в контексте не выглядит надежным. Если приложение остановится, то все пользователи пропадут, это плохо.

Чтобы не поднимать базу, можно сохранить файл

2023-05-17 11:49 UTC, bogdanburich commented on app/utils.py
> +async def try_send_message(customer_counter: int,
> Возвращает для удобства просто.

Из названия функции она не должна этого возвращать + ты передаешь счетчик, потом снова его возвращаешь, выглядит как бессмысленное действие.

2023-05-17 11:59 UTC, bogdanburich commented on app/utils.py
> +    for customer_id in context.chat_data:
Я логику с добавлением контекст не увидел и не понял, как это работает. Теперь понял, нужно поискать альтернативное решение.

2023-05-17 12:00 UTC, bogdanburich commented on app/bot.py
> +            context.chat_data[user_id] = "send_message"
Ага, теперь понял, спасибо

2023-05-17 12:01 UTC, bogdanburich commented on app/utils.py
> +async def try_send_message(customer_counter: int,
Если главная фукнция вызывает эту фукнцию, то она точно так же будет падать

2023-05-17 12:05 UTC, SelfMullerMikhail commented on app/utils.py
> +    for customer_id in context.chat_data:
Альтернативным решением было использование специального класса ConversationHandler, но он не срабатывает не получение сообщений. Только на открытие диалога. Но сообщения не считывает.
Я так понял это происходит потому, что это работает в асинхроне. И вроде как есть специальная библиотека, для работы с tg в асинхронне - aiogram.

2023-05-17 12:05 UTC, SelfMullerMikhail commented on app/utils.py
> +    for customer_id in context.chat_data:
> Я логику с добавлением контекст не увидел и не понял, как это работает. Теперь понял, нужно поискать альтернативное решение.

Альтернативным решением было использование специального класса ConversationHandler, но он не срабатывает не получение сообщений. Только на открытие диалога. Но сообщения не считывает.
Я так понял это происходит потому, что это работает в асинхроне. И вроде как есть специальная библиотека, для работы с tg в асинхронне - aiogram.

2023-05-17 12:06 UTC, SelfMullerMikhail commented on app/utils.py
> +    call_del = 'delete__'
> Вот это как будто бы лишним выглядит. Зачем отправлять сообщение "0 people got message", если его нужно просто удалить? Непонятно.

Извини, не понял(

2023-05-17 12:06 UTC, SelfMullerMikhail commented on app/utils.py
> +async def try_send_message(customer_counter: int,
> 

Для этого и выношу, что бы в отдельной функции обработать исключение. Что бы главная функция не падала

2023-05-17 12:10 UTC, SelfMullerMikhail commented on app/utils.py
> +async def try_send_message(customer_counter: int,
> Если главная фукнция вызывает эту фукнцию, то она точно так же будет падать

Для этого и выношу, что бы в отдельной функции обработать исключение. Что бы главная функция не падала

2023-05-17 12:11 UTC, bogdanburich commented on app/utils.py
> +async def try_send_message(customer_counter: int,
А почему нельзя обработать исключение в основной фукнции?

2023-05-17 18:30 UTC, SelfMullerMikhail commented
- Через "ConversationHandler" не вышло, т.к. у него все таки немного другое назначение, и даже применяя его, все равно пришлось бы отталкиваться от состояния пользователя, которое и так применялось ранее. Собственно логику оставил, протестировал ее в разных комбинациях вызовах методов. Работает без перебойно. Да и сама организация через (send, dell) - кажется весьма удобной. Можно несколько раз отправить одно и тоже сообщение. Или разные.

 - Пользователи добавляются в БД после кнопки /start, если они ее нажмут еще раз, пройдет проверка на наличие и повторно не добавится.
 
 - Сообщения отправляются всем участникам бота, кроме человека который отправил это (отправлять могут только админы, и кнопки есть только у них)
 
 - После отправки такого сообщения, пользователю возвращается сколько сообщений было доставлено.

2023-05-18 03:42 UTC, bogdanburich commented on app/sql_connector.py
> +                           VALUES({user_id}, '{state}');''')
Зачем пустое поле state?

2023-05-18 03:43 UTC, bogdanburich commented on app/utils.py
> +        pass
Можно изменять поле state, если сообщение не удалось отправить

2023-05-18 03:43 UTC, bogdanburich commented on app/utils.py
> +        if cust != user_id:
Можно просто удалить user_id из массива и не делать эту проверку

2023-05-18 03:44 UTC, bogdanburich commented on app/utils.py
> +            await try_send_message(message_counter, bot, cust, text_message)
Давай не будем выносить в отдельную функцию

2023-05-18 03:47 UTC, bogdanburich commented on app/users_id.db
Файл базы данных не должен находиться в репозитории.

Для этой задачи подготовь миграции: скрипт создания базы данных и таблицы.

Например: https://david.rothlis.net/declarative-schema-migration-for-sqlite/

2023-05-18 03:49 UTC, bogdanburich commented on app/config.py
> +BD_FILE = os.path.join(BASE_DIR, 'users_id.db')
Неудачное название для базы, стоит поменять. Название базы данных должно отражать содержание не только одной таблицы или поля, а всей сути.

Например, если это база данных для приложение fyst_fest, то она может так и называться.

2023-05-18 03:51 UTC, bogdanburich commented on app/utils.py
> +                           bot: ContextTypes.DEFAULT_TYPE, customer_id: int,
Разве экземляр бота относится к ContextTypes.DEFAULT_TYPE? Если не ошибаюсь, то это экземляр класса Bot.

2023-05-18 03:52 UTC, bogdanburich commented on app/bot.py
>  def check_creds() -> bool:
Сюда можно добавить проверку, что база данных существует, иначе приложение не будет работать, как ожидается.

2023-05-18 03:55 UTC, bogdanburich commented on app/bot.py
> +    if user is None:
Сюда стоит добавить изменение состояния, переключатель для пользователя: если пользователь активен, то state = active и сообщения отправляются. Если при попытке отправить сообщение была получена ошибка, то пользовать становится inactive и сообщение даже не нужно пытаться отправить. Поле state можно переименовать в is_active и это будет булево значение, чтобы его можно было удобно проверить:

if user.is_active:
    send_message...

2023-05-18 04:02 UTC, bogdanburich commented on app/utils.py
> +async def send_messages(update: Update, context: ContextTypes.DEFAULT_TYPE):
Непонятно, почему эта фукнция в utils, а не bot.py. В utils стоит вынести общие для нескольких хэндлеров фукнции, эта фукнция будет использоваться только в рамках отправки сообщений

2023-05-18 04:03 UTC, bogdanburich commented on app/utils.py
> +    message = f'{SEND_QUESTION}{message_text}'
Эту фукнцию стоит сделать более абстрактной, ведь ее планируется использовать и в двух других хэндлерах, насколько я понимаю: Request Song, Send Photos

2023-05-18 04:11 UTC, bogdanburich commented on app/bot.py
> +    if user is None:
if not user лаконичнее

2023-05-18 04:12 UTC, bogdanburich commented on app/bot.py
> +    flag = False
Название переменной нужно изменить

2023-05-18 04:14 UTC, bogdanburich commented on app/bot.py
> +    if flag is False:
if not flag лаконичнее

2023-05-18 04:14 UTC, bogdanburich commented on app/bot.py
> +    if flag is False:
Будет читаться намного лучше, если выбрать хорошее название переменной

2023-05-18 08:49 UTC, SelfMullerMikhail commented on app/sql_connector.py
> +                           VALUES({user_id}, '{state}');''')
> Зачем пустое поле state?

Я добавил его для того, если вдруг потребуется хранить какое то состояние людей. Мало ли. Много это не занимает)
п. - предусмотрительность. Что бы потом БД не трогать.

2023-05-18 08:50 UTC, SelfMullerMikhail commented on app/utils.py
> +        pass
> Можно изменять поле state, если сообщение не удалось отправить и не отправлять его пользователям, которые заблочили бота.

Думал вообще удалять пользователя. Но потом подумал что мб не доставлено из за разных факторов. Но менять состояние - да. Я до этого не додумался. Исправлю)

2023-05-18 08:52 UTC, SelfMullerMikhail commented on app/utils.py
> +        if cust != user_id:
> Можно просто удалить user_id из массива и не делать эту проверку

Почему? Этот же массив держит всех пользователей. Если мы его удалим, то следующий админ ему уже сообщение не отправит ведь. Пока тот снова не сделал /start

2023-05-18 08:53 UTC, SelfMullerMikhail commented on app/utils.py
> +            await try_send_message(message_counter, bot, cust, text_message)
> Давай не будем выносить в отдельную функцию

А как тогда сделать так, что бы функция при исключение не останавливалась. подскажи пожалуйста.

2023-05-18 08:54 UTC, SelfMullerMikhail commented on app/users_id.db
> Файл базы данных не должен находиться в репозитории.
> 
> Для этой задачи подготовь миграции: скрипт создания базы данных и таблицы. При запуске приложения проверяется, существует ли база данных. Если нет - запускается скрипт миграции.
> 
> Например: https://david.rothlis.net/declarative-schema-migration-for-sqlite/

Понял, принял)

2023-05-18 08:55 UTC, SelfMullerMikhail commented on app/utils.py
> +                           bot: ContextTypes.DEFAULT_TYPE, customer_id: int,
> Разве экземляр бота относится к ContextTypes.DEFAULT_TYPE? Если не ошибаюсь, то это экземляр класса Bot.

Верно. Я ошибся.

2023-05-18 09:00 UTC, SelfMullerMikhail commented on app/bot.py
> +    if user is None:
> Сюда стоит добавить изменение состояния, переключатель для пользователя: если пользователь активен, то state = active и сообщения отправляются. Если при попытке отправить сообщение была получена ошибка, то пользовать становится inactive и сообщение даже не нужно пытаться отправить. Поле state можно переименовать в is_active и это будет булево значение, чтобы его можно было удобно проверить:
> 
> if user.is_active: send_message...

Я могу так сделать, то не может ли возникнуть проблемы в результате не корректной работы бота? К примеру по опыту работы с ТГ, бывает возникают исключения (превышен порог ожидания времени, и происходит исключение, но в самом телеграмме месседж сохраняется и позже доходит. таким образом мыполучаем и исключение и отправляем сообщение). У нас так работает сейчас с отправкой pdf. До обработки исключения отправки pdf в 1/3 случаев я получал и бд и исключение.

2023-05-18 09:18 UTC, bogdanburich commented on app/utils.py
> +        if cust != user_id:
> Этот же массив держит всех пользователей.

Ты при каждой отправке заново получаешь массив из базы и удаляешь автора из массива.
При новой отправке сообщения ты получишь изначальный массив из базы, где будет автор предыдущего сообщения.

2023-05-18 09:19 UTC, bogdanburich commented on app/bot.py
>  def check_creds() -> bool:
check_creds() вызывается при запуске приложения. Сейчас если отсутствует env-переменная, то приложение не запустится и простой будет sys.exit(). Аналогично с базой: если базы нет, то приложение не должно запускаться.

2023-05-18 09:21 UTC, bogdanburich commented on app/sql_connector.py
> +                           VALUES({user_id}, '{state}');''')
Заранее добавлять поля, которые ты не используешь нет никакого смысла, так не делается. Нужно поле - добавил, не нужно - удалил. Зачем тебе лишний код, который ничего не делает?

В комментах ниже отписал, как можно использовать, только переименуй на is_active, это будет булево поле

2023-05-18 11:25 UTC, bogdanburich commented on app/CREATE_TABLE_users.sql
Внутри app создай папку migrations, перемести в нее

2023-05-18 11:26 UTC, bogdanburich commented on app/bot.py
> +    message_counter = [0]
Почему это массив?

2023-05-18 11:27 UTC, bogdanburich commented on app/bot.py
> +    if customers:
Лишняя проверка

2023-05-18 11:28 UTC, SelfMullerMikhail commented on app/bot.py
> +    message_counter = [0]
> Почему это массив?

Потому что если передать int, то это будет как значимый тип данных, а нам нужно передать ссылочный иначе каунт так и останется 0

2023-05-18 11:29 UTC, bogdanburich commented on app/bot.py
> +    user_id = update.callback_query.from_user.id
user_id -> admin_id, тогда ниже можно сделать customers -> users

2023-05-18 11:29 UTC, SelfMullerMikhail commented on app/bot.py
> +    if customers:
> Лишняя проверка

Если никому не отправится сообщение, то при итерирование будет исключение

2023-05-18 11:30 UTC, SelfMullerMikhail commented on app/bot.py
> +    message_counter = [0]
> Почему это массив?

блин, это было когда отправка сообщений была в другой функции. сейчас исправлю

2023-05-18 11:30 UTC, bogdanburich commented on app/CREATE_TABLE_users.sql
> +  user_id INTEGER NOT NULL,
user_id в рамках базы должны быть UNIQUE

2023-05-18 11:32 UTC, bogdanburich commented on app/bot.py
> +    await context.bot.send_message(chat_id=chat_id, text='Choose one:',
Вроде бы это уже не нужно, у нас нигде не изменяется клавиатура и не будет?
Можно отправить однажды вместе с HELLO_TEXT при первом сообщении.

2023-05-18 11:33 UTC, bogdanburich commented on app/bot.py
> +    dialog_flag = SqlConnector.get_user(user_id)
Переменная все еще не отображает своего содержания. Он называется dialog_flag, а содержит user_id 🤔

2023-05-18 11:34 UTC, bogdanburich commented on app/bot.py
> +    if context.chat_data.get(user_id) and user_id in ADMIN_IDS:
Почему user_id берется из контекста, а не из update?

2023-05-18 11:37 UTC, bogdanburich commented on app/bot.py
> +            SqlConnector.set_user_state(user_id, True)
Почему здесь изменяется состояние пользователя?

Если пользователь заблокировал бота, то ему снова нужно нажать /start -> состояние пользователя на True должно меняться только в /start

2023-05-18 11:40 UTC, bogdanburich commented on app/utils.py
> +    context.chat_data[user_id] = message_text
Бессмысленная операция, она ничего не делает

2023-05-18 11:44 UTC, bogdanburich commented on app/utils.py
> +    call = f'send__{message_text}'
По-моему это можно переписать нормально, используя другую структуру данных. То, что ты здесь пытаешься сделать: передать два значения в одной строке. Для этого есть структура данных - словарь:

{
    'action': 'send,
    'message': 'message_text'
}

Можно не переделывать, но код в куче мест будет лучше читаться и не будет ненужных .split

2023-05-18 11:51 UTC, bogdanburich commented on app/bot.py
> +    if customers:
Откуда там должно появиться исключение? Массив пустой, он просто не будет итерироваться. Попробуй запусти код:

array = []

for i in array:
    print(i)

2023-05-18 12:00 UTC, SelfMullerMikhail commented on app/bot.py
> +    if customers:
> 

нашел проблему.
    customers = list(customers)
    customers.remove(user_id)
   возвращает пустой массив
   а
   customers = list(customers).remove(user_id)
   возвращает обьект None

2023-05-18 12:12 UTC, SelfMullerMikhail commented on app/bot.py
> +            SqlConnector.set_user_state(user_id, True)
> Почему здесь изменяется состояние пользователя?
> 
> Если пользователь заблокировал бота, то ему снова нужно нажать /start, у него нет другого способа взаимодействовать с ботом -> состояние пользователя на True должно меняться только в /start

Не понимаю тогда смысл, в этом столбце. Сейчас это несет функционал на переключение в режим ввода текста.
Если оставить как прежде, то переменная будет одна на всех.

2023-05-18 12:18 UTC, SelfMullerMikhail commented on app/utils.py
> +    call = f'send__{message_text}'
> По-моему это можно переписать нормально, используя другую структуру данных. То, что ты здесь пытаешься сделать: передать два значения в одной переменной. Для этого есть структура данных - словарь:
> 
> { 'action': 'send', 'message': message_text }
> 
> Можно не переделывать, но код в куче мест будет лучше читаться и не будет ненужных .split

Я сделал так, т.к. у меня был опыт со словарем и callBack'ами. 
Не работает так, как хотелось бы. Не держит call_back словарей. (
Что я делал? В call_back назначал словарь, и ТГ не выдавал ошибку, а просто передавал ранее назначенные колбеки. Как это работает, я не разобрался за 5 часов

2023-05-18 12:48 UTC, bogdanburich commented on app/CREATE_TABLE_users.sql
> +  state INTEGER NOT NULL DEFAULT 0
нужно переименовать на is_active

2023-05-18 12:48 UTC, bogdanburich commented on app/bot.py
> +            SqlConnector.set_user_state(user_id, True)
Смысл только в том, чтобы не пытаться отправить сообщения тем, кто заблокировал бота

2023-05-18 13:05 UTC, bogdanburich commented on app/utils.py
> +    call = f'send__{message_text}'
Хорошо, а почему нельзя положить в строку словарь и затем конвертировать?
Получится же лучше, чем сейчас есть

2023-05-18 13:42 UTC, bogdanburich commented on app/bot.py
> +    chat_id = update.message.from_user.id
Это user_id

2023-05-18 13:44 UTC, bogdanburich commented on app/config.py
> +SCRIPT_FILE = os.path.join(SCRIPT_FILE, SCRIPT_FILE_NAME)
SCRIPT_FILE = os.path.join(BASE_DIR, f'migrations/{SCRIPT_FILE_NAME}')

2023-05-18 13:44 UTC, bogdanburich commented on app/migrations/CREATE_TABLE_users.sql
> +  is_active INTEGER NOT NULL DEFAULT 1
Почему INTEGER, а не BOOLEAN?

2023-05-18 13:46 UTC, SelfMullerMikhail commented on app/migrations/CREATE_TABLE_users.sql
> +  is_active INTEGER NOT NULL DEFAULT 1
> Почему INTEGER, а не BOOLEAN?

https://www.sqlite.org/datatype3.html
По моему там такого нет

2023-05-18 13:47 UTC, SelfMullerMikhail commented on app/config.py
> +SCRIPT_FILE = os.path.join(SCRIPT_FILE, SCRIPT_FILE_NAME)
> SCRIPT_FILE = os.path.join(BASE_DIR, f'migrations/{SCRIPT_FILE_NAME}')

А почему нельзя просто её определить в config?

2023-05-18 13:50 UTC, bogdanburich commented on app/config.py
> +SCRIPT_FILE = os.path.join(SCRIPT_FILE, SCRIPT_FILE_NAME)
Можно и так, но у тебя переменная переопределяется зачем-то

2023-05-18 13:51 UTC, bogdanburich commented on app/config.py
> +SCRIPT_FILE = os.path.join(SCRIPT_FILE, SCRIPT_FILE_NAME)
Можно:

MIGRATIONS = os.path.join(BASE_DIR, 'migrations')

SCRIPT_FILE = os.path.join(MIGRATIONS, SCRIPT_FILE_NAME)

2023-05-18 13:59 UTC, merged